# Generated by Django 3.1.7 on 2021-05-01 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210501_1011'),
        ('quiz', '0002_attempt_attemptanswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='users.group'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='users.teacher'),
        ),
    ]
