# Generated by Django 3.2.5 on 2021-07-04 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210501_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='quiz_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='quiz_duration',
            field=models.IntegerField(default=0),
        ),
    ]
