# Generated by Django 3.2.5 on 2021-07-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20210704_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_right_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
