# Generated by Django 3.2.5 on 2021-07-06 08:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_question_question_right_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='quiz_creation_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 7, 6, 8, 59, 44, 168933, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='quiz_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
