# Generated by Django 3.2.5 on 2021-07-07 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20210706_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attemptanswers',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='attemptanswers',
            name='attempt',
        ),
        migrations.AddField(
            model_name='attempt',
            name='question',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='attempt_questions', to='quiz.question'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='AttemptAnswers',
        ),
    ]
